### ISSUE TITLE
what feature space do you use to compute dissimilarity?

### ISSUE THREAD

**Issue by ShellingFord221** [Stanford-ILIAD/batch-active-preference-based-learning#1]
Hi, in your paper, Section 3.1, you maximize conditional entropy to select a batch of samples. In medoid selection, you first cluster samples and then select medoids. I wonder what feature space do you use to compute Euclidean distance? Thanks.

**Comment by ebiyik** [comment]
Hello,

We use the same set of features as for the reward function. The features are specific to the domain. For the five tasks we experimented, the features are verbally described in Section 4.1.
In the code, you can see the feature definitions in [models.py](https://github.com/Stanford-ILIAD/batch-active-preference-based-learning/blob/master/models.py) for each task.

Let me know if you have any other questions.
